project:
  name: Fethiye Outage Bot
  debug: true
  environment: development

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: outage_db
  sslmode: disable
  migrations: migrations
  driver: pgx

crawlersurl:
  muski: https://www.muski.gov.tr/
  aydem: https://www.admelektrik.com.tr/assets/js/data/ADM/outages.json

searchconfig:
  simratio: 0.4
  levratio: 4

schedulerconfig:
  fetch_period: '@every 30m'