project:
  name: Fethiye Outage Bot
  debug: true
  environment: development
  
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: outage_db
  sslmode: disable
  migrations: migrations
  driver: pgx

crawlersurl:
  muski: https://www.muski.gov.tr/
  aydem: https://www.admelektrik.com.tr/assets/js/data/ADM/outages.json

botconfig:
  user_state_life_time: 12


schedulerconfig:
  fetch_period: '@every 30m'
  map_clean_period: '@every 12h'
  alert_send_period: '@every 10m'

loggerconfig:
  level: debug
  encoding: json
  outputPaths:
  - stdout
  - "/tmp/logs"
  errorOutputPaths:
  - stderr
  initialFields: {}
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase