version: '3.1'

services:

  db:
    container_name: outage_db
    image: postgres
    restart: always 
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outage_db
