name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o outage_bot ./cmd/

      # - name: Test
      #   run: go test -v ./...
      - name: Transfer
        uses: actions/upload-artifact@v3
        with:
          name: outage_bot
          path: outage_bot        

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: outage_bot

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: outage_bot
          target: outage_bot

  copy-file:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add token to env
        run:  sed -i "4a Environment=OUTAGE_TELEGRAM_APITOKEN=${{ secrets.OUTAGE_TELEGRAM_APITOKEN }}" outageBot.service

      - name: Copy service file
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: outageBot.service
            target: /etc/systemd/system/

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Copy config file
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: config.yml
            target: /outage_bot/

      - name: Copy docker file
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: docker-compose.yml
            target: /outage_bot/
            
      - name: Copy migration files
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: migrations/20230213161100_merged_migration.sql, 20230213174400_insert_districts.sql 
            target: /outage_bot/migrations/  

  up-docker-container:
    runs-on: ubuntu-latest
    needs: [copy-file]
    steps:    
      - name: Run compose
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              docker compose -f /outage_bot/docker-compose.yml build  && docker compose -f /outage_bot/docker-compose.yml up
  restart-service:
    runs-on: ubuntu-latest
    needs: [up-docker-container]
    steps:
      - name: Restarts the service
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              chmod +x outage_bot/outage_bot && sudo systemctl daemon-reload && sudo systemctl restart outageBot.service && sudo systemctl status outageBot.service            